config/routes.rb
Rails.application.routes.draw do
  root 'sensors#index'
  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'sensors#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :sensors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  belongs_to :user
  has_many :values
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sensors

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/value.rb
class Value < ApplicationRecord
  belongs_to :sensor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :avatar])
        #devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :avatar) }
        devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password, :avatar])
        #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :avatar) }
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = current_user.sensors.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @temp = CoAP::Client.new.get_by_uri("coap://#{@sensor.address}/sensors/temperature").payload
    @light = CoAP::Client.new.get_by_uri("coap://#{@sensor.address}/sensors/ambient_light").payload
    @time = Time.now.change(:min => 0)
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)
    @sensor.user_id = current_user.id

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to root_path, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to root_path, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name, :node_type, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/layouts/_sidebar.html.erb
  <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <ul class="nav menu">
      <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li><br>
      <li class=<%= 'active' if current_page?(root_path) %>><%= link_to '<svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard'.html_safe, root_path %></li>
      <li class=<%= 'active' if current_page?(new_sensor_path) %>><%= link_to '<svg class="glyph stroked wireless router"><use xlink:href="#stroked-wireless-router"/></svg> Add New Sensor'.html_safe, new_sensor_path %></li>
      <li class=<%= 'active' if current_page?(edit_registration_path(current_user)) %>><%= link_to '<svg class="glyph stroked male user "><use xlink:href="#stroked-male-user"/></svg> My Profile'.html_safe, edit_registration_path(current_user) %></li>
      <li><%= link_to '<svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Logout'.html_safe, destroy_user_session_path, method: :delete%>
    </ul>

  </div><!--/.sidebar-->

app/views/layouts/_top_nav.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to (image_tag "logo3.png"), root_path, {:class => 'navbar-brand', :style => 'padding-top:10px;'} %>
        <ul class="user-menu">
          <li class="dropdown pull-right">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> <%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to '<svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Profile'.html_safe, edit_user_registration_path %></li>
              <li><%= link_to '<svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Logout'.html_safe, destroy_user_session_path, method: :delete%></li>
            </ul>
          </li>
        </ul>
      </div>

    </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Internet of Penguins</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render "layouts/top_nav" if current_user %>

    <%= render "layouts/sidebar" if current_user %>

    <%= yield %>


    <script>
      !function ($) {
        $(document).on("click","ul.nav li.parent > a > span.icon", function(){
          $(this).find('em:first').toggleClass("glyphicon-minus");
        });
        $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
      }(window.jQuery);

      $(window).on('resize', function () {
        if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
      })
      $(window).on('resize', function () {
        if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
      })
    </script>
  </body>
</html>

app/views/layouts/dashboard_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIotBackend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/datepicker3.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">
    <script src="js/lumino.glyphs.js"></script>
  </head>

  <body>

    <%= render "dashboard/layouts/top_nav" %>

    <%= render "dashboard/layouts/sidebar" %>

    <%= yield %>




    <script src="js/jquery-1.11.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/chart.min.js"></script>
    <script src="js/chart-data.js"></script>
    <script src="js/easypiechart.js"></script>
    <script src="js/easypiechart-data.js"></script>
    <script src="js/bootstrap-datepicker.js"></script>
    <script>
      !function ($) {
        $(document).on("click","ul.nav li.parent > a > span.icon", function(){
          $(this).find('em:first').toggleClass("glyphicon-minus");
        });
        $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
      }(window.jQuery);

      $(window).on('resize', function () {
        if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
      })
      $(window).on('resize', function () {
        if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
      })
    </script>
  </body>
</html>

app/views/sensors/_form.html.erb
<%= form_for @sensor, :html => { :class => "form-horizontal sensor" } do |f| %>

  <% if @sensor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sensor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :node_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :node_type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:node_type) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sensors_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sensors/edit.html.erb
<%- model_class = Sensor -%>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
      <ol class="breadcrumb">
        <li><%= link_to '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'.html_safe, sensors_path%></li>
        <li class="active"> <svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"/></svg> Edit Sensor </li>
      </ol>
    </div><!--/.row-->

    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Edit</h1>
      </div>
    </div><!--/.row-->


    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">Editing Sensor</div>
          <br>
            <%= render :partial => 'form' %>
            <br>
        </div>
      </div>
    </div><!--/.row-->
  </div>  <!--/.main-->

app/views/sensors/index.html.erb
<%- model_class = Sensor -%>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg> Home</a></li>
      </ol>
    </div><!--/.row-->

    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
      </div>
    </div><!--/.row-->


    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">Sensors Overview</div>
            <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:name) %></th>
                <th><%= model_class.human_attribute_name(:type) %></th>
                <th><%= model_class.human_attribute_name(:address) %></th>
                <th><%= model_class.human_attribute_name(:created_at) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @sensors.each do |sensor| %>
                <tr>
                  <td><%= link_to sensor.name, sensor_path(sensor) %></td>
                  <td><%= sensor.node_type %></td>
                  <td><%= sensor.address %></td>
                  <td><%=l sensor.created_at %></td>
                  <td>
                    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                edit_sensor_path(sensor), :class => 'btn btn-default btn-xs' %>
                    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                sensor_path(sensor),
                                :method => :delete,
                                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                :class => 'btn btn-xs btn-danger' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div><!--/.row-->

    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-6">
        <div class="panel panel-blue panel-widget ">
          <div class="row no-padding">
            <div class="col-sm-3 col-lg-5 widget-left">
              <svg class="glyph stroked wireless router"><use xlink:href="#stroked-wireless-router"/></svg>
            </div>
            <div class="col-sm-9 col-lg-7 widget-right">
              <div class="large"><%= current_user.sensors.count %></div>
              <div class="text-muted">Sensor(s) working now</div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-6">
        <div class="panel panel-orange panel-widget">
          <div class="row no-padding">
            <div class="col-sm-3 col-lg-5 widget-left">
              <svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg>
            </div>
            <div class="col-sm-9 col-lg-7 widget-right">
              <div class="large">
              <% count = 0 %>
              <% current_user.sensors.each do |sensor| %>
                <% count = sensor.values.count + count %>
              <% end %>
              <%= count%>
              </div>
              <div class="text-muted">Values collected from your sensors</div>
            </div>
          </div>
        </div>
      </div>
    </div><!--/.row-->
  </div>  <!--/.main-->

  <script>
    !function ($) {
        $(document).on("click","ul.nav li.parent > a > span.icon", function(){
            $(this).find('em:first').toggleClass("glyphicon-minus");
        });
        $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
    }(window.jQuery);

    $(window).on('resize', function () {
      if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
    })
    $(window).on('resize', function () {
      if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
    })
  </script>

app/views/sensors/new.html.erb
<%- model_class = Sensor -%>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
      <ol class="breadcrumb">
        <li><%= link_to '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'.html_safe, sensors_path%></li>
        <li class="active"> <svg class="glyph stroked pencil"><use xlink:href="#stroked-pencil"/></svg> Add Sensor </li>
      </ol>
    </div><!--/.row-->

    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Add New Sensor</h1>
      </div>
    </div><!--/.row-->


    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">Add new sensor to your account</div>
          <br>
            <%= render :partial => 'form' %>
            <br>
        </div>
      </div>
    </div><!--/.row-->
  </div>  <!--/.main-->

app/views/sensors/show.html.erb
<%- model_class = Sensor -%>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
      <ol class="breadcrumb">
        <li><%= link_to '<svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg>'.html_safe, sensors_path%></li>
        <li class="active"> <svg class="glyph stroked wireless router"><use xlink:href="#stroked-wireless-router"/></svg> <%= @sensor.name %> </li>
      </ol>
    </div><!--/.row-->



    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading"><%= @sensor.name %>  Details</div>
            <dl class="dl-horizontal">
              <br>
              <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
              <dd><%= @sensor.name %></dd>
              <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
              <dd><%= @sensor.node_type %></dd>
              <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
              <dd><%= @sensor.address %></dd>
              <dt><strong><%= model_class.human_attribute_name(:temperature) %>:</strong></dt>
              <dd><%= @temp %></dd>
              <dt><strong><%= model_class.human_attribute_name(:light) %>:</strong></dt>
              <dd><%= @light %></dd>
              <br>
            </dl>
          </div>
        </div>
      </div><!--/.row-->


    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">Last 24 Hours of your <%= @sensor.name %></div>
          <div class="panel-body">
            <div class="canvas-wrapper">
              <canvas class="main-chart" id="line-chart" height="200" width="600"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div><!--/.row-->
  </div>  <!--/.main-->



  <script>
    var lineChartData = {
      labels : [
      <% 24.downto(0).each do |i| %>
        "<%= (@time - i.hour).hour%>:00",
      <% end %>
      ],
      datasets : [
        {
          label: "My First dataset",
          fillColor : "rgba(252, 184, 115, 1)",
          strokeColor : "rgba(220,220,220,1)",
          pointColor : "rgba(250, 133, 15, 1)",
          pointStrokeColor : "#fff",
          pointHighlightFill : "#fff",
          pointHighlightStroke : "rgba(220,220,220,1)",
          data : [
          <% 24.downto(1).each do |i| %>
          <% light_avg = 0 %>
          <% time_range = (@time - i.hour)..(@time - (i-1).hour) %>
            <% current_user.sensors.find(@sensor.id).values.where(created_at: time_range).each do |value| %>
              <% light_avg += value.light.to_f %>
            <% end %>

            <% count = current_user.sensors.find(@sensor.id).values.where(created_at: time_range).count %>

            <% count = 1 if (count == 0) %>

            <% light_avg = (light_avg/count).round(2) %>
            <%= light_avg %>,
          <% end %>

          ]
        },
        {
          label: "My Second dataset",
          fillColor : "rgba(48, 164, 255, 0.2)",
          strokeColor : "rgba(48, 164, 255, 1)",
          pointColor : "rgba(48, 164, 255, 1)",
          pointStrokeColor : "#fff",
          pointHighlightFill : "#fff",
          pointHighlightStroke : "rgba(48, 164, 255, 1)",
          data : [
          <% 24.downto(1).each do |i| %>
          <% temp_avg = 0 %>
          <% time_range = (@time - i.hour)..(@time - (i-1).hour) %>
            <% current_user.sensors.find(@sensor.id).values.where(created_at: time_range).each do |value| %>
              <% temp_avg += value.temperature.to_f %>
            <% end %>

            <% count = current_user.sensors.find(@sensor.id).values.where(created_at: time_range).count %>

            <% count = 1 if (count == 0) %>

            <%= temp_avg = (temp_avg/count).round(2) %>,
          <% end %>

          ]
        }
      ]

    }
  </script>